# Generated by Django 2.1 on 2019-01-30 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('registro', models.CharField(blank=True, max_length=12)),
                ('cpf', models.CharField(max_length=14, null=True, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Atendente'), (2, 'Profissional')], null=True, verbose_name='Tipo (Permissão)')),
                ('area_atuacao', models.CharField(blank=True, choices=[('FS', 'Fisioterapeuta'), ('TA', 'Terapeuta ocupacional'), ('FN', 'Fonoaudiólogo(a)'), ('NT', 'Nutricionista'), ('PS', 'Psicólogo(a'), ('DT', 'Dentista'), ('EF', 'Educador(a) Físico(a)'), ('ET', 'Esteticista'), ('MT', 'Musicoterapeuta'), ('EN', 'Enfermeiro(a)'), ('PP', 'Psicopedagogo(a)'), ('AT', 'Atendente')], max_length=2, null=True)),
                ('quantidade_atend', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('horario_trabalho', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profissionais',
                'verbose_name': 'Profissional',
            },
        ),
    ]
