# Generated by Django 2.1 on 2019-01-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='quantidade_atend',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
    ]
