# Generated by Django 2.1 on 2019-01-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0002_auto_20190117_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Atendente'), (2, 'Profissional')], null=True),
        ),
    ]
