# Generated by Django 2.1 on 2019-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0003_auto_20190118_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='area_atuacao',
            field=models.CharField(blank=True, choices=[('FS', 'Fisioterapeuta'), ('TA', 'Terapeuta ocupacional'), ('FN', 'Fonoaudiólogo(a)'), ('NT', 'Nutricionista'), ('PS', 'Psicólogo(a'), ('DT', 'Dentista'), ('EF', 'Educador(a) Físico(a)'), ('ET', 'Esteticista'), ('MT', 'Musicoterapeuta'), ('EN', 'Enfermeiro(a)'), ('PP', 'Psicopedagogo(a)'), ('AT', 'Atendente')], max_length=2, null=True),
        ),
    ]
