# Generated by Django 2.1 on 2019-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_usuarios', '0004_auto_20190126_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='horario_trabalho',
            field=models.TextField(blank=True),
        ),
    ]
