# Generated by Django 2.1 on 2019-01-30 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Convenios',
                'verbose_name': 'Convenio',
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(blank=True, choices=[('', '*Sexo'), ('F', 'Feminino'), ('M', 'Masculino')], max_length=1, verbose_name='Sexo')),
                ('especialidade', models.CharField(blank=True, choices=[('FS', 'Fisioterapeuta'), ('TA', 'Terapeuta ocupacional'), ('FN', 'Fonoaudiólogo(a)'), ('NT', 'Nutricionista'), ('PS', 'Psicólogo(a'), ('DT', 'Dentista'), ('EF', 'Educador(a) Físico(a)'), ('ET', 'Esteticista'), ('MT', 'Musicoterapeuta'), ('EN', 'Enfermeiro(a)'), ('PP', 'Psicopedagogo(a)'), ('AT', 'Atendente')], max_length=2, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Principal')),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('observacao', models.TextField(blank=True, max_length=60)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name_plural': 'Listas de Espera',
                'verbose_name': 'Lista de Espera',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Convenio')),
            ],
            options={
                'verbose_name_plural': 'Procedimentos',
                'verbose_name': 'Procedimento',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name_plural': 'Salas',
                'verbose_name': 'Sala',
            },
        ),
    ]
