# Generated by Django 3.0.3 on 2020-08-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='endereco',
        ),
    ]
