# Generated by Django 2.1 on 2019-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190206_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='nome',
            field=models.CharField(choices=[('particular', 'Particular'), ('unimed', 'Unimed'), ('humanasaude', 'Humana Saúde'), ('saudecaixa', 'Saúde Caixa'), ('intermed', 'Intermed'), ('geapsaude', 'Geap Saúde'), ('fusma', 'Fusma'), ('cassi', 'Cassi')], max_length=40),
        ),
    ]
