# Generated by Django 3.0.3 on 2020-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clinica_sobre_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='sobre_nos',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
