# Generated by Django 3.0.3 on 2022-08-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200808_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='bairro',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='cidade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='keywords',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='clinica',
            name='rua',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinica',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
