# Generated by Django 3.0.3 on 2022-08-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220816_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='rua',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
