# Generated by Django 2.1 on 2019-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='responsavel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
