# Generated by Django 2.1 on 2019-01-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20190126_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
