# Generated by Django 2.1 on 2019-02-02 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('controle_usuarios', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('PG', 'Pago'), ('PD', 'Pendente')], default='PD', max_length=2)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Procedimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name': 'ContaReceber',
                'verbose_name_plural': 'ContasReceber',
            },
        ),
    ]
