# Generated by Django 2.1 on 2020-07-28 23:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atendimento', '0001_initial'),
        ('agenda', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True)),
                ('valor_total', models.CharField(max_length=20)),
                ('status_pag', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name': 'Conta a pagar',
                'verbose_name_plural': 'Contas a pagar',
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('valor_total_pago', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('valor_pago_dinheiro', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('valor_pago_cartao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('status', models.CharField(choices=[('PG', 'Pago'), ('PD', 'Pendente'), ('FT', 'Faturado'), ('PC', 'Parcial')], default='PG', max_length=2)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('ES', 'Especie'), ('TF', 'Tranferência'), ('CD', 'Cartão de Débito'), ('EC', 'Especie e Cartão'), ('VS', 'Cartão Visa'), ('MC', 'Cartão Mastercard'), ('AE', 'Cartão American Express'), ('CS', 'Cartão Credishop'), ('HP', 'Cartão HyperCard'), ('EO', 'Cartão Elo')], default='ES', max_length=2)),
                ('recebido_por', models.CharField(blank=True, max_length=50, verbose_name='recebido_por')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agenda.Agendamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name': 'ContaReceber',
                'verbose_name_plural': 'ContasReceber',
            },
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_guia', models.DateField()),
                ('numero_guia', models.CharField(blank=True, max_length=20, verbose_name='Numero da guia')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6, null=True)),
                ('servico', models.CharField(blank=True, max_length=50, verbose_name='Serviço')),
                ('procedimento', models.CharField(blank=True, max_length=50, verbose_name='Procedimento')),
                ('cod_procedimento', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('status_pag', models.BooleanField(default=False)),
                ('status_fat', models.BooleanField(default=False)),
                ('status_nf', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimento.Atendimento')),
            ],
            options={
                'verbose_name': 'Faturamento',
                'verbose_name_plural': 'Faturamentos',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('documento', models.FileField(upload_to='recibos/%Y/%m/%d/')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_usuarios.Profissional')),
            ],
        ),
        migrations.AddField(
            model_name='faturamento',
            name='lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Lote'),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='faturamento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional'),
        ),
    ]
