# Generated by Django 2.1 on 2019-02-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.CharField(choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], default='CV', max_length=2),
        ),
    ]
