# Generated by Django 2.1 on 2019-02-06 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
        ('financeiro', '0002_contareceber_forma_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contareceber',
            old_name='valor',
            new_name='valor_total',
        ),
        migrations.AddField(
            model_name='contareceber',
            name='atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='atendimento.Atendimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_pago_cartao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='valor_pago_dinehiro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.CharField(choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('DC', 'Dinheiro e Cartão de crédito'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], default='CV', max_length=2),
        ),
    ]
