# Generated by Django 2.1 on 2019-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20190206_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('DC', 'Dinheiro e Cartão de crédito'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], default='CV', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('PD', 'Pendente')], default='PG', max_length=2),
        ),
    ]
