# Generated by Django 2.1 on 2019-02-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_auto_20190207_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('vencimento', models.DateField(null=True)),
                ('valor_total', models.CharField(max_length=20)),
                ('n_parcela', models.IntegerField(blank=True, choices=[(0, 'Escolha uma opção'), (1, '1x'), (2, '2x'), (3, '3x'), (4, '4x'), (5, '5x'), (6, '6x'), (7, '7x'), (8, '8x'), (9, '9x'), (10, '10x'), (11, '11x'), (12, '12x')], default=1, verbose_name='Nº Da Parcela')),
                ('status_pag', models.BooleanField(default=False)),
                ('forma_pagamento', models.CharField(choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('DC', 'Dinheiro e Cartão de crédito'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_fixa', models.NullBooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Contas a pagar',
                'verbose_name': 'Conta a pagar',
            },
        ),
    ]
