# Generated by Django 2.1 on 2019-02-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_categoria_contapagar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contareceber',
            old_name='valor_pago_dinehiro',
            new_name='valor_pago_dinheiro',
        ),
    ]
