# Generated by Django 2.1 on 2019-02-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_auto_20190212_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('EC', 'Dinheiro e Cartão de crédito'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('EC', 'Dinheiro e Cartão de crédito'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], default='CV', max_length=2, null=True),
        ),
    ]
