# Generated by Django 2.1 on 2019-02-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_auto_20190215_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='cartao_credito',
            field=models.CharField(blank=True, choices=[('VS', 'Visa'), ('MC', 'Mastercard'), ('AE', 'American Express'), ('EO', 'Elo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('EC', 'Dinheiro e Cartão'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], max_length=100),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('CV', 'Convênio'), ('DI', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('EC', 'Dinheiro e Cartão'), ('BB', 'Boleto bancário'), ('TB', 'Transferência bancária'), ('DC', 'Débito em Conta')], default='CV', max_length=2, null=True),
        ),
    ]
