# Generated by Django 2.1 on 2019-01-28 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controle_usuarios', '0001_initial'),
        ('core', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(blank=True, choices=[('AG', 'Agendado'), ('AT', 'Atendido'), ('CC', 'Cancelado'), ('DM', 'Desmarcado')], default='AG', max_length=2)),
                ('observacao', models.TextField(blank=True)),
                ('cancelado', models.TextField(blank=True, max_length=50)),
                ('liberado', models.BooleanField(default=False)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sala')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EV', 'Evolução'), ('AV', 'Avaliação')], max_length=2)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('qp', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('hda', models.TextField(blank=True)),
                ('outras_doencas', models.TextField(blank=True)),
                ('pa', models.CharField(blank=True, max_length=15)),
                ('mmHg', models.CharField(blank=True, max_length=15)),
                ('bpm', models.CharField(blank=True, max_length=15)),
                ('rpm', models.CharField(blank=True, max_length=15)),
                ('inspecao', models.TextField(blank=True)),
                ('palpacao', models.TextField(blank=True)),
                ('exame_fisico1', models.TextField(blank=True)),
                ('exame_fisico2', models.TextField(blank=True)),
                ('exame_complementar', models.TextField(blank=True)),
                ('teste_especifico', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
                ('evolucao', models.TextField(blank=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Convenio')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('quantidade', models.IntegerField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('validade', models.DateField()),
                ('atualizado_em', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='guia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimento.Guia'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Procedimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional'),
        ),
    ]
