# Generated by Django 2.1 on 2020-07-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('controle_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('EV', 'Evolução'), ('AV', 'Avaliação'), ('DM', 'Desmarcado na Hora'), ('FH', 'Justificada na Hora'), ('FN', 'Falta Não Justificada'), ('AR', 'ATendido/Recepção')], max_length=2)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('qtdautorizada', models.IntegerField()),
                ('validade', models.DateField()),
                ('data_autorizacao', models.DateField()),
                ('tipo_guia', models.CharField(choices=[('PV', 'Provisoria'), ('PM', 'Permanente')], max_length=2)),
                ('status', models.CharField(choices=[('I', 'Intercambio'), ('N', 'Normal')], default='N', max_length=1)),
                ('validada', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ativo', models.BooleanField(default=True)),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Procedimento')),
                ('profissional', models.ManyToManyField(to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name': 'Guia',
                'verbose_name_plural': 'Guias',
                'ordering': ['quantidade'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='atendimento.Atendimento')),
                ('encaminhado_por', models.CharField(blank=True, max_length=30, verbose_name='Encaminhado Por')),
                ('queixa', models.TextField(blank=True, max_length=400, verbose_name='Queixa')),
                ('hda', models.TextField(blank=True, max_length=400, verbose_name='HDA/HMA')),
                ('has', models.BooleanField(verbose_name='Hipertensão')),
                ('cardiaca', models.BooleanField(verbose_name='Insuficiência Cardíaca')),
                ('dm', models.BooleanField(verbose_name='Diabetes')),
                ('comorbidade', models.TextField(blank=True, max_length=400, verbose_name='Outras condições de saúde / Comorbidades')),
                ('medicamento', models.CharField(blank=True, max_length=30, verbose_name='Histórico de Medicamentos')),
                ('rotina_familiar', models.TextField(blank=True, max_length=400, verbose_name='Relacionamentos Ex:(Familiar, Infância, Afetivo, Amizades, outra)')),
                ('rotina_diaria', models.TextField(blank=True, max_length=400, verbose_name='Rotina Ex:(Trabalho, Familiar, Pessoal, Escola, outra)')),
                ('dificuldade', models.TextField(blank=True, max_length=400, verbose_name='Dificuldades Ex:(Pessoal, Caracteristicas, Metas, organizações, outra)')),
                ('atividade', models.TextField(blank=True, max_length=400, verbose_name='Atividades  Ex:(Dança, esportes, outra)')),
                ('cirurgia', models.TextField(blank=True, max_length=400, verbose_name='Histórico de Cirurgias ou fraturas')),
                ('exame', models.TextField(blank=True, max_length=400, verbose_name='Exames para Diagnóstico)')),
                ('infeccao', models.TextField(blank=True, max_length=400, verbose_name='Histórico de Infecções)')),
                ('avaliacao', models.TextField(blank=True, max_length=100, verbose_name='Avaliação')),
                ('condulta_prof', models.TextField(blank=True, verbose_name='Condulta Profissional')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='atendimento.Atendimento')),
                ('evolucao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Evolução',
                'verbose_name_plural': 'Evoluções',
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='convenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Convenio'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atendimento.Guia'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Procedimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional'),
        ),
    ]
