# Generated by Django 2.1.5 on 2019-01-17 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('controle_usuarios', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(blank=True, choices=[('AG', 'Agendado'), ('AT', 'Atendido'), ('CC', 'Cancelado')], default='AG', max_length=2)),
                ('observacao', models.TextField(blank=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Sala')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EV', 'Evolução'), ('AV', 'Avaliação')], max_length=2)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('qp', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('hda', models.TextField(blank=True)),
                ('outras_doencas', models.TextField(blank=True)),
                ('pa', models.CharField(blank=True, max_length=15)),
                ('mmHg', models.CharField(blank=True, max_length=15)),
                ('bpm', models.CharField(blank=True, max_length=15)),
                ('rpm', models.CharField(blank=True, max_length=15)),
                ('inspecao', models.TextField(blank=True)),
                ('palpacao', models.TextField(blank=True)),
                ('exame_fisico1', models.TextField(blank=True)),
                ('exame_fisico2', models.TextField(blank=True)),
                ('exame_complementar', models.TextField(blank=True)),
                ('teste_especifico', models.TextField(blank=True)),
                ('tratamento', models.TextField(blank=True)),
                ('evolucao', models.TextField(blank=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.Paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Procedimento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_usuarios.Profissional')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
