# Generated by Django 2.1 on 2019-01-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelado',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
