# Generated by Django 3.0.7 on 2021-03-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='tipo_guia',
            field=models.CharField(choices=[('PV', 'Provisoria'), ('PM', 'Permanente')], default='PM', max_length=2),
        ),
    ]
