# Generated by Django 3.0.7 on 2021-03-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_auto_20210323_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='atividade',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='cardiaca',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='cirurgia',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='comorbidade',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='condulta_prof',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='dificuldade',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='dm',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='encaminhado_por',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='exame',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='has',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='hda',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='infeccao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='rotina_diaria',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='rotina_familiar',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='condulta',
            field=models.TextField(blank=True, max_length=400, verbose_name='Queixa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='familia',
            field=models.TextField(blank=True, max_length=400, verbose_name='Queixa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='patologico',
            field=models.TextField(blank=True, max_length=400, verbose_name='Queixa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='social',
            field=models.TextField(blank=True, max_length=400, verbose_name='Queixa'),
        ),
    ]
